In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3], dtype=np.float32)
print(a)


[1. 2. 3.]


In [10]:
b = np.array([8,5,3],dtype=np.int16)
print(b)        
print(b.dtype)  

[8 5 3]
int16


In [12]:
#input to array
a = [9,8,7]
b=np.asarray(a)
print(b)

[9 8 7]


In [14]:
#np.ones && np.zeros
a = np.ones(7)
print(a)

[1. 1. 1. 1. 1. 1. 1.]


In [17]:
b=np.ones([7,5])
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
a = np.empty([5,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
import numpy as np
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [ ]:
#identity matrix - np.eye()

In [27]:
a = np.array([2,5,7])
b=np.array([2,4,5])
z=a+b
x=a-b
c=a*b
p=np.sqrt(b)
print(p)
print(z)
print(x)
print(c)

[1.41421356 2.         2.23606798]
[ 4  9 12]
[0 1 2]
[ 4 20 35]


In [36]:
import numpy as np
a = np.array([5, 8, 12, 19, 25])
b = np.array([[3, 17, 24], [29, 38, 46], [55, 61, 78]])
c = np.array([1, 9, 15, 27, 33, 45, 59, 73, 81, 97])

print(a[0])
print(b[1, 2])


5
46


In [37]:
print(a[1:4])
print(b[:2, 1:])

[ 8 12 19]
[[17 24]
 [38 46]]


In [38]:

print(c[::2])
print(b[:, 1:3])

[ 1 15 33 59 81]
[[17 24]
 [38 46]
 [61 78]]


In [39]:
print(a[[0, 2, 4]])
print(a[a > 3])

[ 5 12 25]
[ 5  8 12 19 25]


In [40]:
print(b.flatten())

[ 3 17 24 29 38 46 55 61 78]


In [41]:
d = np.array([6, 7, 8])
print(np.concatenate((a, d)))

[ 5  8 12 19 25  6  7  8]


In [42]:
d = np.array([6, 7, 8])
print(np.concatenate((a, d)))

[ 5  8 12 19 25  6  7  8]


In [43]:
d = np.array([6, 7, 8])
print(np.concatenate((a, d)))
print(np.stack((a[:3], d)))
print(np.array_split(a, 3))
print(np.append(a, [6, 7]))
print(np.insert(a, 1, [9, 10]))
print(np.delete(a, [1, 2]))
a.resize((2, 3))
print(a)


[ 5  8 12 19 25  6  7  8]
[[ 5  8 12]
 [ 6  7  8]]
[array([5, 8]), array([12, 19]), array([25])]
[ 5  8 12 19 25  6  7]
[ 5  9 10  8 12 19 25]
[ 5 19 25]
[[ 5  8 12]
 [19 25  0]]


In [45]:
import numpy as np

#1
a = np.random.rand(2, 3, 4)
b = np.random.rand(3, 4)
result_1 = a * b
print(result_1)

[[[0.55150821 0.22385045 0.66875363 0.20658546]
  [0.42140186 0.33350839 0.10863966 0.01161484]
  [0.19312315 0.10108845 0.51555581 0.48349768]]

 [[0.10650751 0.60469873 0.06274056 0.23603949]
  [0.5470869  0.10034009 0.54226635 0.04132612]
  [0.10307389 0.42856847 0.71518746 0.07925758]]]


In [47]:
#2
def elementwise_operations(c, d):
    try:
        return {
            "addition": c + d,
            "subtraction": c - d,
            "multiplication": c * d,
            "division": c / d
        }
    except ValueError:
        return "Broadcasting not possible"

c = np.random.rand(2, 3)
d = np.random.rand(1, 3)
result_2 = elementwise_operations(c, d)
print(result_2)

{'addition': array([[0.83670465, 0.99239471, 0.83295955],
       [1.54417369, 1.74875621, 1.00794486]]), 'subtraction': array([[-0.34831464, -0.98511342, -0.71537613],
       [ 0.35915439, -0.22875192, -0.54039082]]), 'multiplication': array([[0.1446879 , 0.0035997 , 0.04551465],
       [0.56387013, 0.75145521, 0.18098265]]), 'division': array([[0.41213675, 0.00368205, 0.07594182],
       [1.60615788, 0.76864629, 0.30197201]])}


In [48]:
np1 = np.random.rand(5, 3)
np2 = np.random.rand(5)
outer_product = np1[:, np.newaxis, :] * np2[:, np.newaxis]
print(outer_product)

[[[0.08365692 0.06884372 0.03040406]
  [0.53675671 0.44171272 0.19507746]
  [0.5521751  0.45440096 0.20068108]
  [0.90105927 0.74150789 0.32747864]
  [0.48351066 0.39789499 0.17572586]]

 [[0.07252859 0.0361487  0.02714224]
  [0.46535547 0.23193607 0.17414912]
  [0.47872284 0.23859846 0.17915157]
  [0.78119723 0.38935358 0.292346  ]
  [0.41919239 0.2089281  0.1568736 ]]

 [[0.00892092 0.00395737 0.03139071]
  [0.05723809 0.02539113 0.20140802]
  [0.05888226 0.02612049 0.20719348]
  [0.0960862  0.04262436 0.33810581]
  [0.05156009 0.02287234 0.18142842]]

 [[0.02198728 0.04160429 0.01104846]
  [0.14107403 0.26694005 0.07088875]
  [0.1451264  0.27460792 0.07292504]
  [0.2368225  0.44811513 0.11900171]
  [0.12707955 0.2404597  0.06385662]]

 [[0.01840341 0.066256   0.04431063]
  [0.1180793  0.4251095  0.28430433]
  [0.12147114 0.43732081 0.292471  ]
  [0.198221   0.7136359  0.47726474]
  [0.10636588 0.38293881 0.25610145]]]


In [53]:
yu = np.random.rand(4, 3, 2)
result = yu[::2, ::2, :]
print(result)

[[[0.0809648  0.10174926]
  [0.09235287 0.90187327]]

 [[0.71094309 0.464878  ]
  [0.27548923 0.461035  ]]]


In [52]:
def diagonal_sum(a, b, c):
    k = np.zeros((len(b), len(c)))
    for m in range(len(b)):
        for n in range(len(c)):
            k[m, n] = np.sum(np.diagonal(a, offset=(c[n] - b[m])))
    return k
a = np.random.rand(4, 4)
b = [0, 1]
c = [1, 2]
re = diagonal_sum(a, b, c)
print(re)

[[1.42131564 1.77199497]
 [1.23751542 1.42131564]]


In [55]:
def product_of_means(i):
    row_means = np.mean(i, axis=1)
    col_means = np.mean(i, axis=0)
    return np.outer(row_means, col_means)

i = np.random.rand(3, 4)
res = product_of_means(i)
print(res)

[[0.11412135 0.0793255  0.17964181 0.2339586 ]
 [0.20447652 0.14213117 0.32187256 0.41919447]
 [0.21733981 0.15107242 0.34212105 0.44556533]]


In [56]:
n = np.random.rand(4, 6)
reshaped = n.reshape(2, 2, 6)
flattened = reshaped.reshape(4, 6)
print(reshaped)
print(flattened)

[[[0.88567528 0.67021955 0.9729243  0.7625731  0.7999412  0.11498695]
  [0.1264891  0.42894911 0.99611624 0.16318643 0.27498983 0.12803209]]

 [[0.67527316 0.86525169 0.00845709 0.07601307 0.63207324 0.17757867]
  [0.85481962 0.57556447 0.84392117 0.34612967 0.02751167 0.81103472]]]
[[0.88567528 0.67021955 0.9729243  0.7625731  0.7999412  0.11498695]
 [0.1264891  0.42894911 0.99611624 0.16318643 0.27498983 0.12803209]
 [0.67527316 0.86525169 0.00845709 0.07601307 0.63207324 0.17757867]
 [0.85481962 0.57556447 0.84392117 0.34612967 0.02751167 0.81103472]]


In [57]:
def roll_along_axis(a, positions):
    return np.roll(a, shift=positions, axis=0)

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
positions = 1
res = roll_along_axis(a, positions)
print(res)

[[10 11 12]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [58]:
def replace_with_mean(p, x):
    p = p.copy()
    mask = p == x
    rows, cols = np.where(mask)
    for row, col in zip(rows, cols):
        neighbors = []
        if row > 0:
            neighbors.append(p[row-1, col])
        if row < p.shape[0] - 1:
            neighbors.append(p[row+1, col])
        if col > 0:
            neighbors.append(p[row, col-1])
        if col < p.shape[1] - 1:
            neighbors.append(p[row, col+1])
        p[row, col] = np.mean(neighbors)
    return p

p = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
x = 0
r = replace_with_mean(p, x)
print(r)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
